#Copyright 2020 AskDesis Inc. or its subsidiaries. All Rights Reserved.
#This is the confidential unpublished intellectual property of Askdesis
#Inc, and includes without limitation exclusive copyright and trade
#secret rights of Askdesis Inc throughout the world.


SUPPORTED_COUNTRY_CODE : US
SUPPORTED_COUNTRY : United States
MAX_SMS_EXPIRY_TIME: 5 #SMS expires in 5 minutes after we send it
MAX_SMS_RESEND_TIME: 1 #Client application resend the OTP after one minute if user doesn't enter it
VOTE_RATE: 3 #For rate throttling, user can vote max three times per minute
SECRETS_REGION: #Example : us-east-2 (AWS)

#white listed phone numbers to be used in testing
WHITE_LIST_PHONE_NUMBERS: +11234567890,+12345678900

#Default numbers for the iOS verification process to approve the app
DEFAULT_LOGIN_NUMBERS: +11234567890, +12345678900

CANDIDATE_1: #Candidate 1 name Example - Donald Trump
CANDIDATE_1_IMAGE_URL: #Candidate 1 Image URL 
CANDIDATE_1_LOGO: #Candidate 1 Party logo URL
CANDIDATE_2: #Candidate 2 Example - Joe Biden
CANDIDATE_2_IMAGE_URL: #Candidate 2 Image URL
CANDIDATE_2_LOGO: #Candidate 2 Party logo URL
