#Copyright 2020 AskDesis Inc. or its subsidiaries. All Rights Reserved.
#This is the confidential unpublished intellectual property of Askdesis
#Inc, and includes without limitation exclusive copyright and trade
#secret rights of Askdesis Inc throughout the world.

spring:
  profiles:
    active: prod